version: '3'
services:
  ros2:
    image: robopaas/rosdocked-foxy:labs
    hostname: rosdocked
    environment:
      - ROS_HOSTNAME=rosdocked
      - DISPLAY=novnc:0.0
    depends_on:
      - novnc
  
  novnc:  
    build:
      context: novnc/
      dockerfile: Dockerfile
    hostname: novnc
    environment:
      # Adjust to your screen size
      - DISPLAY_WIDTH= 1920
      - DISPLAY_HEIGHT= 1080
    shm_size: 2gb
    ports:
      - "443:8080"
  

