version: '3'
services:
  rosdocked:
    image: robopaas/rosdocked-kinetic-workspace-included:labs
#   build:
#      context: .
#      dockerfile: Dockerfile
    hostname: rosdocked
    environment:
      - ROS_HOSTNAME=rosdocked
      - DISPLAY=novnc:0.0
    depends_on:
      - novnc
    command: roscore
  
  novnc:  
    build:
      context: ../novnc/
      dockerfile: Dockerfile
    environment:
      # Adjust to your screen size
      - DISPLAY_WIDTH= 1920
      - DISPLAY_HEIGHT= 1080
    shm_size: 2gb
    # ipc: host
    ports:
      - "443:8080"
  

