version: '3'
services:
  ros:
    image: robopaas/rosdocked-noetic-cpu:latest
    hostname: rosdocked
    environment:
      - ROS_HOSTNAME=rosdocked
      - DISPLAY=novnc:0.0
    depends_on:
      - novnc
    command: roscore
    volumes:
      - $PWD:/host

  novnc:  
    image: robopaas/novnc:labs
    hostname: novnc
    environment:
      # Adjust to your screen size
      - DISPLAY_WIDTH= 1920
      - DISPLAY_HEIGHT= 1080
    shm_size: 2gb
    ports:
      - "80:8080"

